import type { Metadata } from "next";
import { auth } from "@/lib/auth";
import AppLayoutClient from "./AppLayoutClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AppLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await auth();

  return <AppLayoutClient user={session?.user}>{children}</AppLayoutClient>;
};

export default AppLayout;
