import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import "../styles/globals.scss";
import ReduxProvider from "@/store/provider";
import { Navigation } from "@/common";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="UTF-8" />
        <meta name="title" content="SpenTrace" />
        <meta name="author" content="Bernard Calma" />
        <meta
          name="description"
          content="Generated by create next app with Redux and Next.js"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
        <meta name="theme-color" content="#000000" />

        {/* For Mobile */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/* <!-- Status bar style: default, black, black-translucent --> */}
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        {/* <!-- Optional: name shown on home screen --> */}
        <meta name="apple-mobile-web-app-title" content="SpenTrace" />
      </head>
      <body className={` ${kanit.variable} antialiased`}>
        <ReduxProvider children={children} />
      </body>
    </html>
  );
}
