import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import "../styles/globals.scss";
import ReduxProvider from "@/store/provider";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${kanit.variable} antialiased`}>
        <ReduxProvider children={children} />
      </body>
    </html>
  );
}
